// 数据类型定义
export type DataType = 'string' | 'integer' | 'decimal' | 'boolean';

// 组件类型
export type ComponentType = 'decision_table' | 'rule' | 'script';

// 组件类型显示名称
export const COMPONENT_TYPE_LABELS: Record<ComponentType, string> = {
  decision_table: '决策表',
  rule: '规则',
  script: '脚本',
};

// 规则组件 - 条件树节点
export interface ConditionNode {
  id: string;
  type: 'group' | 'condition';
  operator?: 'and' | 'or';           // group 时
  children?: ConditionNode[];         // group 时
  leftInput?: string;                 // condition 时 (变量/组件输出引用)
  comparator?: string;                // >, <, ==, >=, <=, !=, contains, in
  rightValue?: string;                // 右侧值
}

export interface RuleComponentConfig {
  conditionTree: ConditionNode;
}

// 脚本组件 - 输出定义 + 代码
export interface ScriptOutput {
  id: string;
  code: string;
  name: string;
  dataType: DataType;
}

export interface ScriptComponentConfig {
  outputs: ScriptOutput[];
  script: string;
}

export type ComponentConfig = RuleComponentConfig | ScriptComponentConfig | Record<string, never>;

// 比较运算符定义
export const COMPARATORS_BY_TYPE: Record<DataType, { value: string; label: string }[]> = {
  string: [
    { value: '==', label: '等于' },
    { value: '!=', label: '不等于' },
    { value: 'contains', label: '包含' },
    { value: 'not_contains', label: '不包含' },
    { value: 'starts_with', label: '开头是' },
    { value: 'ends_with', label: '结尾是' },
    { value: 'in', label: '在列表中' },
  ],
  integer: [
    { value: '==', label: '等于' },
    { value: '!=', label: '不等于' },
    { value: '>', label: '大于' },
    { value: '>=', label: '大于等于' },
    { value: '<', label: '小于' },
    { value: '<=', label: '小于等于' },
  ],
  decimal: [
    { value: '==', label: '等于' },
    { value: '!=', label: '不等于' },
    { value: '>', label: '大于' },
    { value: '>=', label: '大于等于' },
    { value: '<', label: '小于' },
    { value: '<=', label: '小于等于' },
  ],
  boolean: [
    { value: '==', label: '等于' },
    { value: '!=', label: '不等于' },
  ],
};

// 变量定义（用于输入列）
export interface Variable {
  id: string;
  name: string;
  label: string;
  dataType: DataType;
}

// 输入表达式（函数 / 变量 / 常量）
export type FunctionName = 'max' | 'min' | 'tostring';

export interface FunctionDef {
  name: FunctionName;
  label: string;
  argCount: number;
  returnType: DataType;
}

export const FUNCTIONS: FunctionDef[] = [
  { name: 'max', label: 'max（最大值）', argCount: 2, returnType: 'decimal' },
  { name: 'min', label: 'min（最小值）', argCount: 2, returnType: 'decimal' },
  { name: 'tostring', label: 'tostring（转字符串）', argCount: 1, returnType: 'string' },
];

export type InputExpr =
  | { kind: 'variable'; variableId: string; code: string; label?: string; dataType: DataType }
  | { kind: 'constant'; value: string; dataType: DataType }
  | { kind: 'function'; name: FunctionName; args: (InputExpr | null)[] };

export function expressionToString(expr?: InputExpr | null): string {
  if (!expr) return '';
  if (expr.kind === 'variable') return expr.code;
  if (expr.kind === 'constant') {
    if (expr.dataType === 'string') return `"${expr.value}"`;
    return expr.value || '""';
  }
  if (expr.kind === 'function') {
    return `${expr.name}(${expr.args.map(a => expressionToString(a) || '?').join(', ')})`;
  }
  return '';
}

export function inferExprDataType(expr?: InputExpr | null): DataType {
  if (!expr) return 'string';
  if (expr.kind === 'variable' || expr.kind === 'constant') return expr.dataType;
  const def = FUNCTIONS.find(f => f.name === expr.name);
  return def?.returnType || 'string';
}

// 列定义
export interface Column {
  id: string;
  name: string;
  dataType: DataType;
  isInput: boolean; // true = 输入列, false = 输出列
  variableId?: string; // 仅输入列有（兼容旧数据）
  inputExpr?: InputExpr; // 仅输入列有，支持函数/变量/常量表达式
}

// 单元格值
export interface CellValue {
  columnId: string;
  value: string;
}

// 规则行
export interface Rule {
  id: string;
  cells: Record<string, string>; // columnId -> value
  isFallback?: boolean; // 兜底行：无输入条件，永远匹配，只有输出结果
}

// 决策表数据结构
export interface DecisionTableData {
  columns: Column[];
  rules: Rule[];
}

// 决策表元信息
export interface DecisionTableMeta {
  code: string;       // 唯一编码
  name: string;       // 显示名称
  description: string; // 描述说明
}

// 测试状态
export type TestStatus = 'pending' | 'passed' | 'failed' | 'no-match';

// 测试用例
export interface TestCase {
  id: string;
  name?: string;  // 用例名称（可选）
  inputs: Record<string, string>;   // columnId -> 输入值
  expectedOutputs: Record<string, string>; // columnId -> 预期输出
  actualOutputs?: Record<string, string>;  // 实际输出
  status?: TestStatus;   // 执行状态
  matchedRuleId?: string; // 匹配的规则ID
}

// 批量测试结果统计
export interface TestSuiteResult {
  total: number;
  passed: number;
  failed: number;
  noMatch: number;
}

// 备注/需求文档
export interface DecisionTableNotes {
  content: string;              // Markdown 格式的备注内容
  lastUpdated?: Date;           // 最后更新时间
  autoGenerated?: boolean;      // 是否由 AI 自动生成
}

// 完整决策表数据
export interface DecisionTableFullData {
  meta: DecisionTableMeta;
  columns: Column[];
  rules: Rule[];
  notes?: DecisionTableNotes;   // 备注字段
}

// 选中单元格
export interface SelectedCell {
  ruleId: string;
  columnId: string;
}

// 选中区域
export interface SelectionRange {
  startRuleIndex: number;
  endRuleIndex: number;
  startColumnIndex: number;
  endColumnIndex: number;
}

// 验证错误
export interface ValidationError {
  ruleId: string;
  columnId: string;
  message: string;
}

// MOCK_VARIABLES removed — variables are now managed in the database

// 数据类型显示名称
export const DATA_TYPE_LABELS: Record<DataType, string> = {
  string: '字符串',
  integer: '整数',
  decimal: '小数',
  boolean: '布尔值',
};

// 数据类型图标和颜色
export const DATA_TYPE_ICONS: Record<DataType, { icon: string; color: string }> = {
  string: { icon: 'A', color: 'text-blue-500' },
  integer: { icon: '#', color: 'text-green-600' },
  decimal: { icon: '#.', color: 'text-amber-500' },
  boolean: { icon: '⊤', color: 'text-purple-500' },
};

// 生成唯一ID（用于非数据库实体如列、规则行、条件节点等）
export const generateId = (): string => {
  return `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

// 生成 UUID（用于数据库实体如决策表、测试用例等）
export const generateUUID = (): string => {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  // fallback
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

// 验证区间表达式
export const validateRangeExpression = (value: string): { valid: boolean; message?: string } => {
  if (!value) return { valid: true };
  
  // 检查是否是区间表达式
  const rangePattern = /^[\[\(](-?inf|-?\d+\.?\d*),\s*(-?inf|\+?inf|-?\d+\.?\d*)[\]\)]$/;
  const match = value.match(rangePattern);
  
  if (!match) {
    // 检查是否是单值
    if (/^-?\d+\.?\d*$/.test(value)) {
      return { valid: true };
    }
    return { valid: false, message: '格式错误，请输入单值或区间如 (0,100]' };
  }
  
  const [, start, end] = match;
  
  // 验证数值范围
  if (start !== '-inf' && start !== 'inf' && end !== 'inf' && end !== '+inf' && end !== '-inf') {
    const startNum = parseFloat(start);
    const endNum = parseFloat(end);
    if (startNum >= endNum) {
      return { valid: false, message: '区间起始值必须小于结束值' };
    }
  }
  
  return { valid: true };
};

// 验证输出值类型匹配
export const validateOutputValue = (value: string, dataType: DataType): { valid: boolean; message?: string } => {
  if (!value) return { valid: true };
  
  switch (dataType) {
    case 'integer':
      if (!/^-?\d+$/.test(value)) {
        return { valid: false, message: '请输入整数' };
      }
      break;
    case 'decimal':
      if (!/^-?\d+\.?\d*$/.test(value)) {
        return { valid: false, message: '请输入数值' };
      }
      break;
    case 'boolean':
      if (value !== 'true' && value !== 'false') {
        return { valid: false, message: '请选择 true 或 false' };
      }
      break;
  }
  
  return { valid: true };
};
